name: CD release

on:
  push:
    branches: [ "release" ]

  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
    
      - name: Configure SSH AZURE
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/azure-cloud.key
          chmod 600 ~/.ssh/azure-cloud.key
          cat >>~/.ssh/config <<END
          Host azure-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/azure-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AZURE_SSH_USER }}
          SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
          SSH_HOST: ${{ secrets.AZURE_SSH_HOST }}
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarClod Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
         mvn -B verify sonar:sonar \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.organization=guilherme-nunes \
         -Dsonar.projectKey=GONunes_java-api \
         -Dsonar.language=java \
         -Dsonar.java.coveragePlugin=jacoco \
         -Dmaven.test.skip=true
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests package
          
      - name: Deploy de application
        run: |
          ssh azure-cloud "sudo systemctl stop sandbox-app"
          ssh azure-cloud "sudo rm -rf /sandbox/java-app"
          scp target/java-api.jar azure-cloud:/home/github/java-app
          ssh azure-cloud "sudo mv /home/github/java-app /sandbox/java-app"
          ssh azure-cloud "sudo systemctl start sandbox-app"
